# meta-wilhelmos/conf/layer.conf

BBPATH .= ":${LAYERDIR}"

# Explicitly tell BitBake where our .bb files live
BBFILES += " \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*.inc \
"

BBFILE_COLLECTIONS += "wilhelmos"
BBFILE_PATTERN_wilhelmos := "^${LAYERDIR}/"
BBFILE_PRIORITY_wilhelmos = "6"

# You're on Yocto Wrynose (6.0 LTS)
LAYERSERIES_COMPAT_wilhelmos = "wrynose"

# openembedded-layer (meta-oe) is needed for e.g. nano in wilhelmos-image-base
LAYERDEPENDS_wilhelmos = "core openembedded-layer"
